import type { Metadata } from "next";
import "./globals.css";
import { dhyana } from "./fonts";
import "reflect-metadata"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dhyana.className}>
      <head>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
