import type { Metadata } from "next";
import "./globals.css";
import { dhyana } from "./fonts";
import "reflect-metadata"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dhyana.className}>
      <head>
      {/* <script src="https://www.google.com/recaptcha/api.js?render=6LcyB3krAAAAABVOBfqHSsrDxAxR42OqmE33W7fa"></script> */}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
